[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
monitor_filters = 
    send_on_enter  # Sends data only after you hit Enter
    colorize       # Makes output easier to read
lib_deps = 
    adafruit/Adafruit BusIO @ ^1.16.1
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.2
    Wire

build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
